import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import NextAuthProvider from "@/Provider/NextAuthProvider";
import { Toaster } from "react-hot-toast";
import QueryProvider from "./queryProvider/QueryProvider";



// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={'max-w-7xl mx-auto'}
      >
        <QueryProvider>
          <NextAuthProvider>
            <Navbar />
            <Toaster />
            {children}
          </NextAuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
